version: '3'

volumes:
  kristaps-tettest-db:

services:
  mariadb:
    build:
      context: ./mariadb
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - kristaps-tettest-db:/var/lib/mysql

  symfony:
    build:
      context: ./symfony
    depends_on: 
      - mariadb
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@mariadb:3306/${DATABASE_NAME}?serverVersion=mariadb-10.5.4

  web:
    build:
      context: ./angular
    depends_on: 
      - symfony
    ports:
      - "8080:80"

